// Code generated by protoc-gen-go. DO NOT EDIT.
// source: solver.proto

// package name for the buffer will be used later

package serverledge

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// argument
type Request struct {
	OffloadLatencyCloud     *float32    `protobuf:"fixed32,1,req,name=offload_latency_cloud,json=offloadLatencyCloud" json:"offload_latency_cloud,omitempty"`
	OffloadLatencyEdge      *float32    `protobuf:"fixed32,2,req,name=offload_latency_edge,json=offloadLatencyEdge" json:"offload_latency_edge,omitempty"`
	Functions               []*Function `protobuf:"bytes,3,rep,name=functions" json:"functions,omitempty"`
	Classes                 []*QosClass `protobuf:"bytes,4,rep,name=classes" json:"classes,omitempty"`
	CostCloud               *float32    `protobuf:"fixed32,5,req,name=cost_cloud,json=costCloud" json:"cost_cloud,omitempty"`
	MemoryLocal             *float32    `protobuf:"fixed32,10,req,name=memory_local,json=memoryLocal" json:"memory_local,omitempty"`
	CpuLocal                *float32    `protobuf:"fixed32,11,req,name=cpu_local,json=cpuLocal" json:"cpu_local,omitempty"`
	MemoryAggregate         *float32    `protobuf:"fixed32,12,req,name=memory_aggregate,json=memoryAggregate" json:"memory_aggregate,omitempty"`
	UsableMemoryCoefficient *float32    `protobuf:"fixed32,13,req,name=usable_memory_coefficient,json=usableMemoryCoefficient" json:"usable_memory_coefficient,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}    `json:"-"`
	XXX_unrecognized        []byte      `json:"-"`
	XXX_sizecache           int32       `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetOffloadLatencyCloud() float32 {
	if m != nil && m.OffloadLatencyCloud != nil {
		return *m.OffloadLatencyCloud
	}
	return 0
}

func (m *Request) GetOffloadLatencyEdge() float32 {
	if m != nil && m.OffloadLatencyEdge != nil {
		return *m.OffloadLatencyEdge
	}
	return 0
}

func (m *Request) GetFunctions() []*Function {
	if m != nil {
		return m.Functions
	}
	return nil
}

func (m *Request) GetClasses() []*QosClass {
	if m != nil {
		return m.Classes
	}
	return nil
}

func (m *Request) GetCostCloud() float32 {
	if m != nil && m.CostCloud != nil {
		return *m.CostCloud
	}
	return 0
}

func (m *Request) GetMemoryLocal() float32 {
	if m != nil && m.MemoryLocal != nil {
		return *m.MemoryLocal
	}
	return 0
}

func (m *Request) GetCpuLocal() float32 {
	if m != nil && m.CpuLocal != nil {
		return *m.CpuLocal
	}
	return 0
}

func (m *Request) GetMemoryAggregate() float32 {
	if m != nil && m.MemoryAggregate != nil {
		return *m.MemoryAggregate
	}
	return 0
}

func (m *Request) GetUsableMemoryCoefficient() float32 {
	if m != nil && m.UsableMemoryCoefficient != nil {
		return *m.UsableMemoryCoefficient
	}
	return 0
}

type FunctionInvocation struct {
	QosClass             *string  `protobuf:"bytes,1,req,name=qos_class,json=qosClass" json:"qos_class,omitempty"`
	Arrivals             *float32 `protobuf:"fixed32,2,req,name=arrivals" json:"arrivals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionInvocation) Reset()         { *m = FunctionInvocation{} }
func (m *FunctionInvocation) String() string { return proto.CompactTextString(m) }
func (*FunctionInvocation) ProtoMessage()    {}
func (*FunctionInvocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{1}
}

func (m *FunctionInvocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionInvocation.Unmarshal(m, b)
}
func (m *FunctionInvocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionInvocation.Marshal(b, m, deterministic)
}
func (m *FunctionInvocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionInvocation.Merge(m, src)
}
func (m *FunctionInvocation) XXX_Size() int {
	return xxx_messageInfo_FunctionInvocation.Size(m)
}
func (m *FunctionInvocation) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionInvocation.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionInvocation proto.InternalMessageInfo

func (m *FunctionInvocation) GetQosClass() string {
	if m != nil && m.QosClass != nil {
		return *m.QosClass
	}
	return ""
}

func (m *FunctionInvocation) GetArrivals() float32 {
	if m != nil && m.Arrivals != nil {
		return *m.Arrivals
	}
	return 0
}

type Function struct {
	Name                   *string               `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Memory                 *int32                `protobuf:"varint,2,req,name=memory" json:"memory,omitempty"`
	Cpu                    *float32              `protobuf:"fixed32,3,req,name=cpu" json:"cpu,omitempty"`
	Invocations            []*FunctionInvocation `protobuf:"bytes,4,rep,name=invocations" json:"invocations,omitempty"`
	Duration               *float32              `protobuf:"fixed32,5,req,name=duration" json:"duration,omitempty"`
	DurationOffloadedCloud *float32              `protobuf:"fixed32,6,req,name=duration_offloaded_cloud,json=durationOffloadedCloud" json:"duration_offloaded_cloud,omitempty"`
	DurationOffloadedEdge  *float32              `protobuf:"fixed32,7,req,name=duration_offloaded_edge,json=durationOffloadedEdge" json:"duration_offloaded_edge,omitempty"`
	InitTime               *float32              `protobuf:"fixed32,8,req,name=init_time,json=initTime" json:"init_time,omitempty"`
	InitTimeOffloadedCloud *float32              `protobuf:"fixed32,9,req,name=init_time_offloaded_cloud,json=initTimeOffloadedCloud" json:"init_time_offloaded_cloud,omitempty"`
	InitTimeOffloadedEdge  *float32              `protobuf:"fixed32,10,req,name=init_time_offloaded_edge,json=initTimeOffloadedEdge" json:"init_time_offloaded_edge,omitempty"`
	Pcold                  *float32              `protobuf:"fixed32,11,req,name=pcold" json:"pcold,omitempty"`
	PcoldOffloadedCloud    *float32              `protobuf:"fixed32,12,req,name=pcold_offloaded_cloud,json=pcoldOffloadedCloud" json:"pcold_offloaded_cloud,omitempty"`
	PcoldOffloadedEdge     *float32              `protobuf:"fixed32,13,req,name=pcold_offloaded_edge,json=pcoldOffloadedEdge" json:"pcold_offloaded_edge,omitempty"`
	BandwidthCloud         *float32              `protobuf:"fixed32,14,req,name=bandwidth_cloud,json=bandwidthCloud" json:"bandwidth_cloud,omitempty"`
	BandwidthEdge          *float32              `protobuf:"fixed32,15,req,name=bandwidth_edge,json=bandwidthEdge" json:"bandwidth_edge,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *Function) Reset()         { *m = Function{} }
func (m *Function) String() string { return proto.CompactTextString(m) }
func (*Function) ProtoMessage()    {}
func (*Function) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{2}
}

func (m *Function) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Function.Unmarshal(m, b)
}
func (m *Function) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Function.Marshal(b, m, deterministic)
}
func (m *Function) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Function.Merge(m, src)
}
func (m *Function) XXX_Size() int {
	return xxx_messageInfo_Function.Size(m)
}
func (m *Function) XXX_DiscardUnknown() {
	xxx_messageInfo_Function.DiscardUnknown(m)
}

var xxx_messageInfo_Function proto.InternalMessageInfo

func (m *Function) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Function) GetMemory() int32 {
	if m != nil && m.Memory != nil {
		return *m.Memory
	}
	return 0
}

func (m *Function) GetCpu() float32 {
	if m != nil && m.Cpu != nil {
		return *m.Cpu
	}
	return 0
}

func (m *Function) GetInvocations() []*FunctionInvocation {
	if m != nil {
		return m.Invocations
	}
	return nil
}

func (m *Function) GetDuration() float32 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *Function) GetDurationOffloadedCloud() float32 {
	if m != nil && m.DurationOffloadedCloud != nil {
		return *m.DurationOffloadedCloud
	}
	return 0
}

func (m *Function) GetDurationOffloadedEdge() float32 {
	if m != nil && m.DurationOffloadedEdge != nil {
		return *m.DurationOffloadedEdge
	}
	return 0
}

func (m *Function) GetInitTime() float32 {
	if m != nil && m.InitTime != nil {
		return *m.InitTime
	}
	return 0
}

func (m *Function) GetInitTimeOffloadedCloud() float32 {
	if m != nil && m.InitTimeOffloadedCloud != nil {
		return *m.InitTimeOffloadedCloud
	}
	return 0
}

func (m *Function) GetInitTimeOffloadedEdge() float32 {
	if m != nil && m.InitTimeOffloadedEdge != nil {
		return *m.InitTimeOffloadedEdge
	}
	return 0
}

func (m *Function) GetPcold() float32 {
	if m != nil && m.Pcold != nil {
		return *m.Pcold
	}
	return 0
}

func (m *Function) GetPcoldOffloadedCloud() float32 {
	if m != nil && m.PcoldOffloadedCloud != nil {
		return *m.PcoldOffloadedCloud
	}
	return 0
}

func (m *Function) GetPcoldOffloadedEdge() float32 {
	if m != nil && m.PcoldOffloadedEdge != nil {
		return *m.PcoldOffloadedEdge
	}
	return 0
}

func (m *Function) GetBandwidthCloud() float32 {
	if m != nil && m.BandwidthCloud != nil {
		return *m.BandwidthCloud
	}
	return 0
}

func (m *Function) GetBandwidthEdge() float32 {
	if m != nil && m.BandwidthEdge != nil {
		return *m.BandwidthEdge
	}
	return 0
}

type QosClass struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Utility              *float32 `protobuf:"fixed32,2,req,name=utility" json:"utility,omitempty"`
	MaxResponseTime      *float32 `protobuf:"fixed32,3,req,name=max_response_time,json=maxResponseTime" json:"max_response_time,omitempty"`
	CompletedPercentage  *float32 `protobuf:"fixed32,4,req,name=completed_percentage,json=completedPercentage" json:"completed_percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QosClass) Reset()         { *m = QosClass{} }
func (m *QosClass) String() string { return proto.CompactTextString(m) }
func (*QosClass) ProtoMessage()    {}
func (*QosClass) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{3}
}

func (m *QosClass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QosClass.Unmarshal(m, b)
}
func (m *QosClass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QosClass.Marshal(b, m, deterministic)
}
func (m *QosClass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QosClass.Merge(m, src)
}
func (m *QosClass) XXX_Size() int {
	return xxx_messageInfo_QosClass.Size(m)
}
func (m *QosClass) XXX_DiscardUnknown() {
	xxx_messageInfo_QosClass.DiscardUnknown(m)
}

var xxx_messageInfo_QosClass proto.InternalMessageInfo

func (m *QosClass) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *QosClass) GetUtility() float32 {
	if m != nil && m.Utility != nil {
		return *m.Utility
	}
	return 0
}

func (m *QosClass) GetMaxResponseTime() float32 {
	if m != nil && m.MaxResponseTime != nil {
		return *m.MaxResponseTime
	}
	return 0
}

func (m *QosClass) GetCompletedPercentage() float32 {
	if m != nil && m.CompletedPercentage != nil {
		return *m.CompletedPercentage
	}
	return 0
}

type ClassResponse struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	PL                   *float32 `protobuf:"fixed32,2,req,name=pL" json:"pL,omitempty"`
	PC                   *float32 `protobuf:"fixed32,3,req,name=pC" json:"pC,omitempty"`
	PE                   *float32 `protobuf:"fixed32,4,req,name=pE" json:"pE,omitempty"`
	PD                   *float32 `protobuf:"fixed32,5,req,name=pD" json:"pD,omitempty"`
	Share                *float32 `protobuf:"fixed32,6,req,name=share" json:"share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClassResponse) Reset()         { *m = ClassResponse{} }
func (m *ClassResponse) String() string { return proto.CompactTextString(m) }
func (*ClassResponse) ProtoMessage()    {}
func (*ClassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{4}
}

func (m *ClassResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClassResponse.Unmarshal(m, b)
}
func (m *ClassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClassResponse.Marshal(b, m, deterministic)
}
func (m *ClassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClassResponse.Merge(m, src)
}
func (m *ClassResponse) XXX_Size() int {
	return xxx_messageInfo_ClassResponse.Size(m)
}
func (m *ClassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClassResponse proto.InternalMessageInfo

func (m *ClassResponse) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ClassResponse) GetPL() float32 {
	if m != nil && m.PL != nil {
		return *m.PL
	}
	return 0
}

func (m *ClassResponse) GetPC() float32 {
	if m != nil && m.PC != nil {
		return *m.PC
	}
	return 0
}

func (m *ClassResponse) GetPE() float32 {
	if m != nil && m.PE != nil {
		return *m.PE
	}
	return 0
}

func (m *ClassResponse) GetPD() float32 {
	if m != nil && m.PD != nil {
		return *m.PD
	}
	return 0
}

func (m *ClassResponse) GetShare() float32 {
	if m != nil && m.Share != nil {
		return *m.Share
	}
	return 0
}

type FunctionResponse struct {
	Name                 *string          `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	ClassResponses       []*ClassResponse `protobuf:"bytes,2,rep,name=class_responses,json=classResponses" json:"class_responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FunctionResponse) Reset()         { *m = FunctionResponse{} }
func (m *FunctionResponse) String() string { return proto.CompactTextString(m) }
func (*FunctionResponse) ProtoMessage()    {}
func (*FunctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{5}
}

func (m *FunctionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionResponse.Unmarshal(m, b)
}
func (m *FunctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionResponse.Marshal(b, m, deterministic)
}
func (m *FunctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionResponse.Merge(m, src)
}
func (m *FunctionResponse) XXX_Size() int {
	return xxx_messageInfo_FunctionResponse.Size(m)
}
func (m *FunctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionResponse proto.InternalMessageInfo

func (m *FunctionResponse) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *FunctionResponse) GetClassResponses() []*ClassResponse {
	if m != nil {
		return m.ClassResponses
	}
	return nil
}

type Response struct {
	FResponse            []*FunctionResponse `protobuf:"bytes,1,rep,name=f_response,json=fResponse" json:"f_response,omitempty"`
	TimeTaken            *float32            `protobuf:"fixed32,2,req,name=time_taken,json=timeTaken" json:"time_taken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetFResponse() []*FunctionResponse {
	if m != nil {
		return m.FResponse
	}
	return nil
}

func (m *Response) GetTimeTaken() float32 {
	if m != nil && m.TimeTaken != nil {
		return *m.TimeTaken
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "solver.Request")
	proto.RegisterType((*FunctionInvocation)(nil), "solver.FunctionInvocation")
	proto.RegisterType((*Function)(nil), "solver.Function")
	proto.RegisterType((*QosClass)(nil), "solver.QosClass")
	proto.RegisterType((*ClassResponse)(nil), "solver.ClassResponse")
	proto.RegisterType((*FunctionResponse)(nil), "solver.FunctionResponse")
	proto.RegisterType((*Response)(nil), "solver.Response")
}

func init() {
	proto.RegisterFile("solver.proto", fileDescriptor_7779dcc6dfedf133)
}

var fileDescriptor_7779dcc6dfedf133 = []byte{
	// 769 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0x55, 0x9d, 0x4f, 0xdf, 0xb4, 0x49, 0x98, 0x4d, 0x76, 0xbd, 0x5d, 0xad, 0xb4, 0x58, 0x20,
	0x96, 0x3e, 0x64, 0x97, 0x0a, 0xb1, 0x80, 0x10, 0x12, 0x64, 0x8b, 0x84, 0x94, 0x15, 0x60, 0xfa,
	0xc4, 0x8b, 0x35, 0x19, 0x8f, 0x5d, 0x0b, 0xdb, 0xe3, 0x7a, 0xc6, 0xa1, 0xf9, 0x19, 0x3c, 0xf1,
	0x3b, 0xf9, 0x07, 0x68, 0xee, 0x8c, 0x9d, 0xe6, 0x43, 0xbc, 0x54, 0x73, 0xef, 0xb9, 0xe7, 0xcc,
	0xc9, 0xdc, 0x7b, 0x5d, 0x38, 0x97, 0x22, 0xdb, 0xf0, 0x6a, 0x51, 0x56, 0x42, 0x09, 0xd2, 0x37,
	0x91, 0xff, 0x77, 0x07, 0x06, 0x01, 0xbf, 0xaf, 0xb9, 0x54, 0xe4, 0x1a, 0xe6, 0x22, 0x8e, 0x33,
	0x41, 0xa3, 0x30, 0xa3, 0x8a, 0x17, 0x6c, 0x1b, 0xb2, 0x4c, 0xd4, 0x91, 0x77, 0xf6, 0xca, 0x79,
	0xed, 0x04, 0x4f, 0x2c, 0xb8, 0x32, 0xd8, 0x52, 0x43, 0xe4, 0x2d, 0xcc, 0x0e, 0x39, 0x3c, 0x4a,
	0xb8, 0xe7, 0x20, 0x85, 0xec, 0x53, 0x6e, 0xa2, 0x84, 0x93, 0x05, 0xb8, 0x71, 0x5d, 0x30, 0x95,
	0x8a, 0x42, 0x7a, 0x9d, 0x57, 0x9d, 0xd7, 0xa3, 0xeb, 0xe9, 0xc2, 0x7a, 0xfb, 0xc9, 0x02, 0xc1,
	0xae, 0x84, 0x5c, 0xc1, 0x80, 0x65, 0x54, 0x4a, 0x2e, 0xbd, 0xee, 0x7e, 0xf5, 0x6f, 0x42, 0x2e,
	0x35, 0x12, 0x34, 0x05, 0xe4, 0x25, 0x00, 0x13, 0x52, 0x59, 0xdb, 0x3d, 0xf4, 0xe0, 0xea, 0x8c,
	0x31, 0xfb, 0x31, 0x9c, 0xe7, 0x3c, 0x17, 0xd5, 0x36, 0xcc, 0x04, 0xa3, 0x99, 0x07, 0x58, 0x30,
	0x32, 0xb9, 0x95, 0x4e, 0x91, 0x17, 0xe0, 0xb2, 0xb2, 0xb6, 0xf8, 0x08, 0xf1, 0x21, 0x2b, 0x6b,
	0x03, 0x7e, 0x0e, 0x53, 0xcb, 0xa7, 0x49, 0x52, 0xf1, 0x84, 0x2a, 0xee, 0x9d, 0x63, 0xcd, 0xc4,
	0xe4, 0x7f, 0x68, 0xd2, 0xe4, 0x5b, 0x78, 0x5e, 0x4b, 0xba, 0xce, 0x78, 0x68, 0x19, 0x4c, 0xf0,
	0x38, 0x4e, 0x59, 0xca, 0x0b, 0xe5, 0x5d, 0x20, 0xe7, 0x99, 0x29, 0xf8, 0x80, 0xf8, 0x72, 0x07,
	0xfb, 0x1f, 0x80, 0x34, 0x0f, 0xf1, 0x73, 0xb1, 0x11, 0x8c, 0xea, 0x93, 0x76, 0x76, 0x2f, 0x64,
	0x88, 0x3f, 0x15, 0x3b, 0xe2, 0x06, 0xc3, 0x7b, 0xfb, 0x02, 0xe4, 0x12, 0x86, 0xb4, 0xaa, 0xd2,
	0x0d, 0xcd, 0xa4, 0x7d, 0xfa, 0x36, 0xf6, 0xff, 0xed, 0xc2, 0xb0, 0xd1, 0x23, 0x04, 0xba, 0x05,
	0xcd, 0xb9, 0x15, 0xc0, 0x33, 0x79, 0x0a, 0x7d, 0x63, 0x12, 0xa9, 0xbd, 0xc0, 0x46, 0x64, 0x0a,
	0x1d, 0x56, 0xd6, 0x5e, 0x07, 0xf5, 0xf4, 0x91, 0x7c, 0x07, 0xa3, 0xb4, 0x75, 0xd4, 0xf4, 0xe3,
	0xf2, 0xb0, 0x7b, 0x3b, 0xd3, 0xc1, 0xe3, 0x72, 0x6d, 0x32, 0xaa, 0x2b, 0x0c, 0x6c, 0x6f, 0xda,
	0x98, 0x7c, 0x0d, 0x5e, 0x73, 0x0e, 0xed, 0xd0, 0xf0, 0xc8, 0xf6, 0xb1, 0x8f, 0xb5, 0x4f, 0x1b,
	0xfc, 0x97, 0x06, 0x36, 0x4d, 0xfd, 0x0a, 0x9e, 0x9d, 0x60, 0xe2, 0x10, 0x0e, 0x90, 0x38, 0x3f,
	0x22, 0xe2, 0x1c, 0xbe, 0x00, 0x37, 0x2d, 0x52, 0x15, 0xaa, 0x34, 0xe7, 0xde, 0xd0, 0xd8, 0xd1,
	0x89, 0xdb, 0x34, 0xe7, 0xe4, 0x1b, 0x78, 0xde, 0x82, 0x47, 0x7e, 0x5c, 0xe3, 0xa7, 0x29, 0x3e,
	0xf0, 0xf3, 0x0e, 0xbc, 0x53, 0x54, 0x34, 0x64, 0x06, 0x6e, 0x7e, 0xc4, 0x44, 0x43, 0x33, 0xe8,
	0x95, 0x4c, 0x64, 0x91, 0x1d, 0x3b, 0x13, 0xe8, 0xa5, 0xc4, 0xc3, 0x91, 0x0b, 0x33, 0x78, 0x4f,
	0x10, 0x3c, 0xb0, 0xf0, 0x16, 0x66, 0x87, 0x1c, 0xbc, 0xde, 0xcc, 0x1d, 0xd9, 0xa7, 0xe0, 0xdd,
	0x9f, 0xc1, 0x64, 0x4d, 0x8b, 0xe8, 0xaf, 0x34, 0x52, 0x77, 0x56, 0x7f, 0x8c, 0xc5, 0xe3, 0x36,
	0x6d, 0xa4, 0x3f, 0x85, 0x5d, 0xc6, 0x88, 0x4e, 0xb0, 0xee, 0xa2, 0xcd, 0x6a, 0x3d, 0xff, 0x9f,
	0x33, 0x18, 0x36, 0xeb, 0x79, 0x72, 0xe6, 0x3c, 0x18, 0xd4, 0x2a, 0xcd, 0x52, 0xb5, 0xb5, 0xf3,
	0xda, 0x84, 0xe4, 0x0a, 0x3e, 0xca, 0xe9, 0x43, 0x58, 0x71, 0x59, 0x8a, 0x42, 0x72, 0xd3, 0x9f,
	0x8e, 0xdd, 0x32, 0xfa, 0x10, 0xd8, 0x3c, 0xb6, 0xe9, 0x0b, 0x98, 0x31, 0x91, 0x97, 0x19, 0x57,
	0x3c, 0x0a, 0x4b, 0x5e, 0x31, 0x5e, 0x28, 0x9a, 0x70, 0xaf, 0x6b, 0xde, 0xa6, 0xc5, 0x7e, 0x6d,
	0x21, 0x7f, 0x0b, 0x17, 0xe6, 0xa3, 0x61, 0x75, 0x4e, 0xba, 0x1b, 0x83, 0x53, 0xae, 0xac, 0x31,
	0xa7, 0x5c, 0x61, 0xbc, 0xb4, 0x26, 0x9c, 0x72, 0x89, 0xf1, 0x8d, 0xbd, 0xc5, 0x29, 0x6f, 0x30,
	0x7e, 0x6f, 0x67, 0xda, 0x29, 0xdf, 0xeb, 0x56, 0xca, 0x3b, 0x5a, 0x71, 0x3b, 0xba, 0x26, 0xf0,
	0x63, 0x98, 0xb6, 0x1f, 0xb8, 0xff, 0xbb, 0xfd, 0x7b, 0x98, 0xe0, 0x96, 0xb7, 0x6f, 0xa0, 0x77,
	0x5a, 0x6f, 0xda, 0xbc, 0xd9, 0xb4, 0xbd, 0x5f, 0x10, 0x8c, 0xd9, 0xe3, 0x50, 0xfa, 0x6b, 0x18,
	0xb6, 0xfa, 0xef, 0x00, 0xe2, 0x56, 0xc7, 0x3b, 0x43, 0x19, 0xef, 0xe8, 0x73, 0xdb, 0x28, 0xb9,
	0x71, 0x4b, 0x7c, 0x09, 0x80, 0x13, 0xac, 0xe8, 0x9f, 0xbc, 0xb0, 0x4f, 0xe1, 0xea, 0xcc, 0xad,
	0x4e, 0x5c, 0x7f, 0x09, 0xfd, 0xdf, 0x51, 0x84, 0x5c, 0x41, 0x0f, 0x4f, 0x64, 0xd2, 0xc8, 0xda,
	0xff, 0x27, 0x97, 0xd3, 0x5d, 0xc2, 0x88, 0xfe, 0xf8, 0xc9, 0x1f, 0x7e, 0x92, 0xaa, 0xbb, 0x7a,
	0xbd, 0x60, 0x22, 0x7f, 0x93, 0x54, 0xb5, 0x94, 0x02, 0xff, 0xbc, 0x91, 0xbc, 0xda, 0xf0, 0x2a,
	0xd3, 0x13, 0xf5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x48, 0x21, 0x55, 0xaa, 0x06, 0x00,
	0x00,
}
